# Generated by Django 2.0.2 on 2018-02-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='fee',
        ),
    ]
